### ISSUE TITLE
An error occurred starting Docker Compose up

### ISSUE THREAD

**Issue by pitosalas** [hojulian/ruby-on-rails-pg-devcontainer#1]
1. Instructions should include installing and starting docker (and links to howto)

2. Also see the error I got. This was on MacOS, after i issued the vscode command

<img width="296" alt="Screen Shot 2021-03-10 at 6 13 31 PM" src="https://user-images.githubusercontent.com/44681/110710773-74ee0700-81cc-11eb-9d05-00a832804d51.png">

**Comment by hojulian** [comment]
It might be that you already have a postgres instance running on port 5432. You might need to kill that first before running this.

**Comment by pitosalas** [comment]
<img width="1045" alt="Screen Shot 2021-03-11 at 7 16 20 AM" src="https://user-images.githubusercontent.com/44681/110786059-b10b8100-8239-11eb-96b2-db1a0a937a89.png">

I stopped postgres (but didn't uninstall it or anything)

**Comment by hojulian** [comment]
I think I spotted the error in the background your screenshot: Seems like you might need to re-login docker on your computer. This is the related issue: https://github.com/docker/hub-feedback/issues/1098

**Comment by hojulian** [comment]
Re-logging in Docker desktop fixed the issue.
